[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "0eaccc9c09624753efe565a6ecff45a8c3ed7b93"
libc = "glibc"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "3b81f483e9866761479c76b72e229caf1a5ad3acab12b46d5925d0dcbcfa2a62"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.aarch64-linux-gnu.tar.gz"

[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "125e0af91a7cb02dea50abc0c8f8f29a64372b7c"
libc = "musl"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "90896afb474f44fe7672d3be4c714357363baaea989751fd5d5a737fa31342d4"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.aarch64-linux-musl.tar.gz"

[[Libglvnd]]
arch = "armv7l"
callabi = "eabihf"
git-tree-sha1 = "e42693eb52e5b41b0ce04434172df95419a8dc85"
libc = "glibc"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "7e13718ccd4bbacab5c857f5f3a70fd6d6f4f7fa19142945e3450bcef6e4069d"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.armv7l-linux-gnueabihf.tar.gz"

[[Libglvnd]]
arch = "armv7l"
callabi = "eabihf"
git-tree-sha1 = "e9b1fe2b976d2c1955abeedeeca5e9beaaf08ceb"
libc = "musl"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "fdaea638350ceb3851165acea1de490598bc86f4b26acca4a683674a282de03e"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.armv7l-linux-musleabihf.tar.gz"

[[Libglvnd]]
arch = "i686"
callabi = "eabihf"
git-tree-sha1 = "6e1ce920d735ed2d676e738ca3f3b0d9b2e20aee"
libc = "glibc"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "9f98adc1cae757e926c91bb865b48b20320b18c4665583423bf07fa4a927ce28"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.i686-linux-gnu.tar.gz"

[[Libglvnd]]
arch = "i686"
callabi = "eabihf"
git-tree-sha1 = "bae4c3afceb48c42eca08ca91356a9a0ceb0e19c"
libc = "musl"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "7d3006894c60601a0d0db99f318987438a9b54fb181aa52dd368269c939e9e5d"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.i686-linux-musl.tar.gz"

[[Libglvnd]]
arch = "powerpc64le"
callabi = "eabihf"
git-tree-sha1 = "05b022a37ec13e7270acc068a7223fcc4627e7dc"
libc = "glibc"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "6883bfe4cb3c9689ea5faa857d22255190fb719e574019a36a9bcb66821f2571"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.powerpc64le-linux-gnu.tar.gz"

[[Libglvnd]]
arch = "x86_64"
callabi = "eabihf"
git-tree-sha1 = "4091a8fa0dd24a7c8e69c16f5487d81c9fd05d38"
libc = "glibc"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "8d0dd3a83a8c6aeb2af1442d5a24c0275e8c09651b6a0f44ae9d7249e07e3603"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.x86_64-linux-gnu.tar.gz"

[[Libglvnd]]
arch = "x86_64"
callabi = "eabihf"
git-tree-sha1 = "455728bc7298b95b91f3d851441257ede5f336f5"
libc = "musl"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "f26b948d3fbfc195c68a216177df11f37bf1e77e2522c251d21bca832efa4176"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.x86_64-linux-musl.tar.gz"

[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "33263a12d7396e94d9935c398498ae4501b8fb54"
os = "linux"

        [[Libglvnd.download]]
        sha256 = "64eef385bf5d5a55897823b1087a283a8ffb8d5d730618cd23d873e183dd5b37"
        url = "https://github.com/arhik/Libglvnd_jll.jl/releases/download/v.1.7.0/Libglvnd.v1.7.0.x86_64-unknown-freebsd.tar.gz"

